version: '3'
services:
  web:
    image: nginx
    restart: always
    volumes:
      - public_content:/usr/share/nginx/html
    depends_on:
      - generator
  generator:
    command: /app/launch.sh
    restart: always
    volumes:
      - public_content:/app/_site

volumes:
  public_content:
